# ========== 游戏设置 ==========
emulator:
  type: "雷电" # 模拟器类型
  start_cmd: "C:/leidian/LDPlayer9/dnplayer.exe"
  config_file: ""
  emulator_name: emulator-5554 # 雷电模拟器使用多开器请填写该项, 不多开默认为 "emulator-5554"


LOG_PATH: "log"
DELAY: 2

account:
password:

# ========== Logger设置 ==========
DEBUG: True
SHOW_MAP_NODE: False # 黄色舰船图标位置
SHOW_ANDROID_INPUT: True
SHOW_ENEMY_RULES: True
SHOW_FIGHT_STAGE: True
SHOW_CHAPTER_INFO: True
SHOW_MATCH_FIGHT_STAGE: True
SHOW_DECISIVE_BATTLE_INFO: True
SHOW_OCR_INFO: True
log_level: DEBUG

# ========== 日常挂机策略设置 ==========
daily_automation:
  auto_expedition: True # 自动重复远征
  auto_gain_bonus: True # 当有任务完成时自动点击
  auto_bath_repair: True # 空闲时自动澡堂修理

  dock_full_destroy: True # 船坞已满时自动清空，若设置为false则船坞已满后终止所有常规出征任务

  auto_battle: True # 自动打完每日战役次数
  battle_type: "困难潜艇" # 打哪个。可选名称参考"plans/battle/"

  auto_normal_fight: True # 按自定义任务进行常规战
  normal_fight_tasks: # 自动出征任务用列表 [plan名，舰队号，目标成功次数] 表示，按顺序从上往下执行。plan名参考"plans/normal_fight/"
    - [8-5AI, 2, 0]

# 数据信息设置
SHIP_NAME_PATH: ""
PLAN_ROOT: ""
