# ========== 游戏设置 ==========
emulator:
  type: "雷电" # 模拟器类型
  start_cmd: "" # 模拟器的地址，如果留空则自动从注册表中查询 示例: "C:/leidian/LDPlayer9/dnplayer.exe"
  config_file: ""
  emulator_name: emulator-5554 # 雷电模拟器使用多开器请填写该项, 不多开默认为 "emulator-5554"

game_app: "官服" #官服 小米 应用宝
check_update: True # 是否在启动脚本时检查更新

LOG_PATH: "log"
DELAY: 1.5

account:
password:

# ========== Logger设置 ==========
DEBUG: True          #是否开启调试模式，如果为 True，则会输出更多的调试信息。
SHOW_MAP_NODE: False      #是否显示地图节点信息。
SHOW_ANDROID_INPUT: True # 是否显示 Android 输入的信息。
SHOW_ENEMY_RULES: True # 是否显示敌人规则信息。
SHOW_FIGHT_STAGE: True # 是否显示战斗阶段信息。
SHOW_CHAPTER_INFO: True # 是否显示章节信息。
SHOW_MATCH_FIGHT_STAGE: True # 是否显示当前阶段信息。
SHOW_DECISIVE_BATTLE_INFO: True # 是否显示决战信息。
SHOW_OCR_INFO: True    # 是否显示 OCR 识别信息。
log_level: DEBUG # 调试模式 log_level 应该设置为 DEBUGlog


# ========== 调试设置 ==============

CHECK_PAGE: True


# ========== 解装设置 ===========

dock_full_destroy: True # 船坞已满时自动清空，若设置为false则船坞已满后终止所有常规出征任务

# ========== 日常挂机策略设置 ==========
daily_automation:
  auto_expedition: True # 自动重复远征
  auto_gain_bonus: True # 当有任务完成时自动点击
  auto_bath_repair: True # 空闲时自动澡堂修理
  auto_set_support: False # 自动开启战役支援
  auto_battle: True # 自动打完每日战役次数
  battle_type: "困难潜艇" # 打哪个。可选名称参考"plans/battle/"

  stop_maxship: False # 捞满500船时自动停止出击
  quick_repair_limit: 50 #使用快修的上限，一但达到上限将会停止日常出征，以防止没有更换舰队导致快修被耗尽

  auto_exercise: True #自动打完每日的三次演习

  auto_normal_fight: True # 按自定义任务进行常规战
  normal_fight_tasks: # 自动出征任务用列表 [plan名，舰队号，目标成功次数] 表示，按顺序从上往下执行。plan名参考"plans/normal_fight/"
    - [8-5AI, 2, 0]

# =========== 数据信息设置 =============
SHIP_NAME_PATH: ""
PLAN_ROOT: # 计划根目录, 如果缺省则默认为 [python packages 目录]/autowsgr/data/plans
EXTRA_IMAGE_ROOT: null # 额外图像根路径, 用于二次开发
